name: Deploy to Azure Spring App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Use Temurin for Java 17

      - name: Build with Maven
        run: mvn clean package --settings .mvn/settings.xml

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Spring App
        run: |
          az spring app deploy \
            --name estore \
            --resource-group coldev-estore-rg \
            --service coldev-estore \
            --artifact target/estore-0.0.1-SNAPSHOT.jar \
            --runtime-version 17  # Specify Java 17 here
